name: Check code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle install
        run: ./gradlew

      - name: Build
        run: ./gradlew test

      - name: build
        run: ./gradlew build
